### ISSUE TITLE
doc command generates nothing new

### ISSUE THREAD

**Issue by sbeckeriv** [mozilla/chromeless#100]
Mac ox 10.6.7
The checked in docs lacks api information. After running chromeless doc git shows no files changed. I see warnings when I run the command but no errors. I deleted the folder and tried again. I got an error about docs not being there(see pull request). 

Mac-Pro:chromeless becker$ ./chromeless docs
Generating documentation
Missing prerequisites!  I must download xulrunner to run.  Doing so
extracting xulrunner-2.0b7pre.en-US.mac-i386.sdk.tar.bz2
Using Browser HTML at '/Users/becker/trash/chromeless/examples/first_browser/index.html'
WARNING, skipping module due to malformed docs (api-utils/lib/app-strings.js):
  Can't determine what this block documents (from @function, @property, @class, @module) at line 79
WARNING, skipping module due to malformed docs (api-utils/lib/es5.js):
  can't determine property name at line 189
WARNING, skipping module due to malformed docs (api-utils/lib/events.js):
  unrecognized tag: @example at line 56
WARNING, skipping module due to malformed docs (api-utils/lib/list.js):
  Can't determine what this block documents (from @function, @property, @class, @module) at line 63
WARNING, skipping module due to malformed docs (api-utils/lib/observer-service.js):
  unrecognized tag: @version at line 42
WARNING, skipping module due to malformed docs (api-utils/lib/tab-browser.js):
  can't determine function name at line 325
WARNING, skipping module due to malformed docs (api-utils/lib/traits.js):
  can't determine property name at line 76
WARNING, skipping module due to malformed docs (api-utils/lib/xpcom.js):
  @return not allowed in @property block at line 145
WARNING, skipping module due to malformed docs (api-utils/lib/content/loader.js):
  Can't determine what this block documents (from @function, @property, @class, @module) at line 115
WARNING, skipping module due to malformed docs (api-utils/lib/content/worker.js):
  Can't determine what this block documents (from @function, @property, @class, @module) at line 78
WARNING, skipping module due to malformed docs (api-utils/lib/tabs/tab.js):
  Can't determine what this block documents (from @function, @property, @class, @module) at line 57
WARNING, skipping module due to malformed docs (api-utils/lib/traits/core.js):
  unrecognized tag: @example at line 63
WARNING, skipping module due to malformed docs (api-utils/lib/windows/loader.js):
  Can't determine what this block documents (from @function, @property, @class, @module) at line 69
WARNING, skipping module due to malformed docs (api-utils/lib/windows/tabs.js):
  Can't determine what this block documents (from @function, @property, @class, @module) at line 54
WARNING, skipping module due to malformed docs (chromeless-kit/lib/events.js):
  can't determine function name at line 1
WARNING, skipping module due to malformed docs (chromeless-kit/lib/net.js):
  can't determine function name at line 101
WARNING, skipping module due to malformed docs (chromeless-kit/lib/ui/tray.js):
  can't determine function name at line 41
Created docs in /Users/becker/trash/chromeless/build/docs.

**Comment by taboca** [comment]
I see you using extracting xulrunner-2.0b7pre.en-US.mac-i386.sdk.tar.bz2. Can you pull the recent version of Chromeless -- it should be using XulRunner 2.0  = http://releases.mozilla.org/pub/mozilla.org/xulrunner/releases/2.0/sdk/xulrunner-2.0.en-US.mac-i386.sdk.tar.bz2. Let me know.

**Comment by sbeckeriv** [comment]
I am synced up to sha 475a63611cee539950d06fd59cdfafcb53646330 and it still does not generate docs for me. It also still generates the warnings.

**Comment by lloyd** [comment]
static documentation is output to `build/docs`  notice that last line of output: 

```
Created docs in /Users/becker/trash/chromeless/build/docs.
```

please re-open if I'm missing something!

**Comment by sbeckeriv** [comment]
My confusion. The docs dir is just the templates for the documentation. Thanks.
