### ISSUE TITLE
Config differences in branches causes xulrunner to be reinstalled

### ISSUE THREAD

**Issue by sbeckeriv** [mozilla/chromeless#101]
I have a branch with an old _config.py file. Every time i switch branches I need to reinstall xulrunner.  I want to work with the master and I am trying to figure out why my git commands are not updating my branch's config.

I can see a few valid reasons for need different versions of xulrunner.  Perhaps it could be installed in a folder with a version number. 

Not super important.

**Comment by lloyd** [comment]
Not so sure about this one.  There already is a local cache, so all that's really happening is the proper version of xulrunner is being unpacked into build/ from a cache directory also within build/.  We could make this go a little bit faster with some symlink trickery, but that would introduce platform differences on windows.

I'm inclined to just leave it how it is, so I'm closing this issue.  If you feel strongly about this though or have other suggestions about how to improve the experience, please reopen.

**Comment by sbeckeriv** [comment]
I am ok with it being closed. The xulrunner code was cached. 

At this point I consider it a warning that my git is out of date.
