### ISSUE TITLE
domElem.contentWindow is null 

### ISSUE THREAD

**Issue by sbeckeriv** [mozilla/chromeless#102]
info: Uncaught-Exception: 'domElem.contentWindow is null' in file 'resource://jid0-ve0baysox4snijgmmjrgl4kfm2w-api-utils-lib/securable-module.js -> resource://jid0-ve0baysox4snijgmmjrgl4kfm2w-chromeless-kit-lib/web-content.js' at line 74, col 0 (222)

This is caused by the pm attach line. I am using the "enableSystemPrivileges":true setting.

 var newBrowser = makeBrowser();
  var uniqueId   = Math.random();
  var browserUnique = "browser_unique_"+uniqueId;
  browserTabs.push(newBrowser);
  newBrowser.setAttribute("id",browserUnique);

  var pm = wc.ProgressMonitor();
  pm.attach(newBrowser);

**Comment by sbeckeriv** [comment]
It turns out I need to attach my new browser to the dom before I can attach it to a progress monitor. If this is by design please close the bug.

**Comment by taboca** [comment]
yes. :) I was gonna say that. Sorry the sample creates an elemnt first and does nothing. Maybe we can move that makeBrowser to be part of the newTab code and  make the code simpler. Feel free to patch the thumbnail example if you are confortable. Maybe from this interaction we can come up with something cool here.

**Comment by taboca** [comment]
Maybe another thing here is us to throw an exception, from the require module = web-content, that teaches this important requirement ( frame has to be attached to the DOM ). 

Another note here is that we could do the whole attach also based on DOMNodeInsertion ( DOM Mutation events ). So like a DOM-based Mutation Patcher approach -- please feedback.

**Comment by sbeckeriv** [comment]
I think a clear exception is a good idea.

I am digging the idea of DOM Mutation events. You could then say any iframe created will always have these events triggering and the code need not worry about attaching or removing progress monitors. Even if this does not become part of chromeless I think I will use this pattern.
