### ISSUE TITLE
apidocs.json location needs to be corrected

### ISSUE THREAD

**Issue by sbeckeriv** [mozilla/chromeless#103]
I think I got the docs thing figured out. 

/docs is the base for the documents
/build/docs/packages/ is where the apidocs.json is built to

The problem now is that main.js:768 is looking in the chromeless/docs/packages/apidocs.json not the build directory. 

1) Move apidocs.json to the docs folder after build 
or
2) Move the location of the docs in the json to the build directory.

3) fix the status==500 logic. the status for loading a local file but failing is 0
4) main.js:553 fails 
apidocs is null
 file:///Users/becker/trash/chromeless/docs/js/main.js
 Line 553

**Comment by lloyd** [comment]
oh, the way I usually view docs on disk is by loading `build/docs/index.html` into firefox.  Not `docs/index.html`.  Does that make sense?  

The idea here is that all build output is tucked under the build/ directory, so you can  just `rm -rf build/` to return your checked out repo to a pristine state (that's effectively `make distclean`).

Does this make more sense?

**Comment by sbeckeriv** [comment]
I see it working correctly in  my Mozilla copy of of the repo. I seem to have broke it in mine.  

could you remove that first level docs from the repro?

**Comment by lloyd** [comment]
no, cause the top level docs/ directory holds documentation templates.  if I remove it, I will have broken the doc generation by taking away the templates.

Maybe we can take a step back, I'm a little confused what problem you're experiencing?

**Comment by sbeckeriv** [comment]
I thought /docs was the folder where the docs lived.  No real problem here just confusion.
