### ISSUE TITLE
can't access frame content or "where my escalated privileges are?"

### ISSUE THREAD

**Issue by 3demax** [mozilla/chromeless#104]
I got this error while trying to access frame content

Traceback (most recent call last):
  File "resource://app/main.js", line 100, in 
    console.log("frame_content " + document.getElementById('contentFrame').contentDocument)
Error: Permission denied to access property 'valueOf'

**Comment by davidmurdoch** [comment]
Is enableSystemPrivileges  set to true in appinfo.json?

**Comment by 3demax** [comment]
Wow, thanks a lot! :D
Little fix: in appinfo.json
This definitely must be in a wiki.

By the way, is there any way to override all the nested frames security and go even deeper? (if content page also contains frames, access to content of which is needed too)

**Comment by davidmurdoch** [comment]
Can the main application html not do this now? I thought you could (using jQuery):

```
<script>
    $("iframe").contents().find("iframe").contents().each(function(){
        $("body", this).html("Injecting content into nested iframe.");
    });
</script>
```

You should be cautious when using enableSystemPrivileges because this functionality may change or be depreciated since the developers don't seem to be very comfortable with allowing System Privileges (personally, I'm all for it).

**Comment by 3demax** [comment]
Ok, I'll try harder.
I'm for it too. IMHO, without that feature chromeless will be useless

**Comment by davidmurdoch** [comment]
There are other ways to inject into cross-domain iframes via chromeless. Web-content.js will do a lot of the work for you (http://mozilla.github.com/chromeless/#module/chromeless-kit/web-content) but still doesn't get you as far as enableSystemPrivileges, yet. 

For instance, with enableSystemPrivileges you can perform cross-domain ajax with jQuery just by setting $.support.cors = true. While there is a kit for x-domain ajax (xhr.js) it would require "duck-punching" (http://paulirish.com/2010/duck-punching-with-jquery/) jQuery to get it to work just right.
