### ISSUE TITLE
Zoom to inner browser content 

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#116]
I created a little zoom out function ( fullZoom ) in some of my repositories -- I wanted to see what you think of this: 

it's here: 

( 06-05 ) 3 commits with sample
https://github.com/taboca/Chromeless-Community-Labs-/commits/master

marcio
PS: And if it is hot, I wonder if it is possible to send a pull request from a separated project on GitHub. Notice this is not my taboca/chromeless github official fork. It's another project that has upstream mozilla/chromeless. Github UI did not let me do via the web interface, probably because it's not tracking as a fork right?

**Comment by lloyd** [comment]
merged in e1684bd0a0e2a99004dcd92b27ee7766dc0af951
