### ISSUE TITLE
[help needed] Saving profile for future use

### ISSUE THREAD

**Issue by zalun** [mozilla/chromeless#117]
I'd like to use chromeless to create a few psudo applications for the website I run quite often (evernote, jsfiddle, ...).

The profile is always saved in /tmp/{hashtag} directory, and hashtag is different for every run.
Is there a possibility to choose a profile for the web content?
Ideally I'll be able to save the profiles under {HOME}/.chromeless/{URL}/ directory

**Comment by lloyd** [comment]
What platform are you on?

If you run the `file_write` demo, where does the file in question get saved?  For me on OSX, it's properly placed in the `~/Library/Application Support` folder

```
$ ./chromeless tests/file_write
...
info: wrote to: /Users/lth/Library/Application Support/My Chromeless App/Profiles/o92k3os0.default/output.txt
```

**Comment by zalun** [comment]
Linux
info: wrote to: /tmp/tmpJmBgj3.mozrunner/output.txt

**Comment by davidmurdoch** [comment]
wouldn't "tmp" be because he is running chromeless from the command line? e.g. `./chromeless tests/file_write`. You should "appify" chromeless first, slap it into your /opt/ directory and run it from there. It should then use a more permanent location, I think.

`chromeless appify tests/file_write`

**Comment by lloyd** [comment]
Oh, nice davidmurdoch.  You're absolutely right.

zalun, this is by design.  Any reason you wouldn't want to "appify" your little pseudo apps?

**Comment by zalun** [comment]
I didn't even knew of such option :) I will check as soon as

**Comment by zalun** [comment]
Working fine, thanks

**Comment by lloyd** [comment]
yay!

**Comment by zalun** [comment]
indeed - I've got now Evernote application :)
next thing would be having many browser sessions in one app.
To make the multiuser Twitter application... But that's nothing really urgent

**Comment by davidmurdoch** [comment]
You could probably do ghetto rig this yourself using the cookie manager and localStorage.
