### ISSUE TITLE
Untitled window

### ISSUE THREAD

**Issue by apoole7** [mozilla/chromeless#119]
ubuntu 10.10
chromeless 0.3

Package apps are grouped in window list probably due window titles all being "Untitled Window".

Is there a way to set the window title to the App name

**Comment by lloyd** [comment]
aha,  reopened issue #81, which is probably the same issue here.  

How about this.  Default window title is Application Name.  If, however, application code has a title (the html node `html > head > title` exists), the contents of that will be used.

the only trick in implementing this is detecting javascript initiated title change and updating the window title without polling.

**Comment by apoole7** [comment]
I think that that sounds perfect, would it be similar to how firefox works? page title - Application Name
So in the webian "world" it would read: "some web page title - Webian"
