### ISSUE TITLE
'TypeError: null is not a function' in file 'javascript:null()'

### ISSUE THREAD

**Issue by olivermontes** [mozilla/chromeless#124]
in any web page have this error:

<code>
info: Uncaught-Exception: 'TypeError: null is not a function' in file 'javascript:null()'
</code>

**Comment by olivermontes** [comment]
info: Uncaught-Exception: 'JSON.parse' in file 'http://connect.facebook.net/es_ES/all.js' at line 9, col 0 (228)

**Comment by davidmurdoch** [comment]
You are going to need to provide some more information on how to reproduce this issue

**Comment by lloyd** [comment]
what @davidmurdoch said!  please reopen with steps to reproduce.
