### ISSUE TITLE
Chromeless/Webian & jQuery Ajax on file:/// urls

### ISSUE THREAD

**Issue by fetard** [mozilla/chromeless#126]
Using file:/// urls & Webian, Ajax calls launched by jQuery are not possible, the error flag is returned each time, using the following test code :

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
        <title>Test</title>

        <script type="text/javascript" src="jquery-1.6.1.min.js"></script>
        <script type="text/javascript">

  jQuery.ajax({
  url: "http://free.fr",
    complete: function(){
   alert("complete");
  },
  success: function(){
   alert("success");
  },
  error: function(jqXHR, textStatus, errorThrown){
   alert(jqXHR.toSource()+"|"+textStatus+"|"+errorThrown);
  }
});
        </script> 
    </head> 
    <body> 

    </body> 
</html>
```

**Comment by davidmurdoch** [comment]
Just set `jQuery.support.cors = true;` before your first ajax call.

**Comment by lloyd** [comment]
cross domain requests can be made by using the `xhr` module, or by using the `require` module.  The former is a partially impelmented identical version of XMLHttpRequest without the cross domain restriction, the latter is an abstraction on top of XMLHttp request again, without the cross domain restriction:

http://mozilla.github.com/chromeless/#module/lib/request
