### ISSUE TITLE
Page position & flash objects reset on tab switching

### ISSUE THREAD

**Issue by benfrancis** [mozilla/chromeless#128]
Steps to re-produce (using example tabbed browser):
1. Load a YouTube video in a tab
2. Scroll down to the video and press play
3. Switch to a different tab
4. Switch back to YouTube tab

Expected outcome:
YouTube video continues playing whilst switching tabs

Actual outcome:
YouTube video stops when change to a different tab, then when change back to the YouTube tab, the page is scrolled back to the top and the video starts again from the start

Is this just due to this particular implementation of tabs, or is this an inherent characteristic of using an iFrame in this way?

**Comment by davidmurdoch** [comment]
hippygeek, you should visit the #chromeless channel http://irc.mozilla.org/

**Comment by davidmurdoch** [comment]
https://github.com/webianproject/shell/pull/2
