### ISSUE TITLE
improve the child process API

### ISSUE THREAD

**Issue by lloyd** [mozilla/chromeless#130]
There have been multiple community requests to improve the process API, specifically to make it possible to asynchronously control spawned processes and to control their stdinput and output.

Here [a thread](http://groups.google.com/group/mozilla-labs/browse_thread/thread/541431b4e5ba3a03) where various implementation options were discussed, along with some references to potentially interesting code.

**Comment by dylanpyle** [comment]
I'd really love to see the child process situation improved. I'm currently building an app on Chromeless that really depends on the ability to read stdout. We're currently having to resort to hacks like piping output to a file and reading from there, which isn't really a long-term option.
