### ISSUE TITLE
Provide DEB/RPM packages

### ISSUE THREAD

**Issue by niutech** [mozilla/chromeless#131]
Please provide DEB and RPM packages of Chromeless so that it could be installable like XULrunner. And then others could develop their packages depending on Chromeless package.

**Comment by benfrancis** [comment]
Am I right in thinking this is dependent on the shared runtime issue, as Chromeless currently goes and gets its own version of XULRunner?

What would it take for a Chromeless package to work with a XULRunner package listed as a dependency? And is this how it should be packaged?
