### ISSUE TITLE
Incompatible with xulrunner 5

### ISSUE THREAD

**Issue by zero79** [mozilla/chromeless#137]
Trying to run chromeless with xulrunner 5 results in the following error.  Note I've manually overridden the xulrunner binary location and set maxVersion=5.0:

Using binary at '/usr/bin/xulrunner-5.0'.
Using profile at '/tmp/tmpoXvAXO.mozrunner'.
**\* LOG addons.manager: Application has been upgraded
**\* LOG addons.xpi: startup
**\* LOG addons.xpi: checkForChanges
**\* LOG addons.xpi: Opening database
**\* LOG addons.xpi: Migrating data from extensions.rdf
**\* LOG addons.xpi: Creating database schema
**\* LOG addons.xpi: No changes found
**\* LOG addons.xpi: Add-ons list is missing, recreating
**\* LOG addons.xpi: Writing add-ons list
error: An exception occurred.
Traceback (most recent call last):
  File "resource://2bb80b33-b94c-42c5-8b0e-6bd35ff11fc8-lib/app-paths.js", line 63, in null
    exports.browserCodeDir = path.join(dirsvc.get("resource:app", Ci.nsIFile).path, "browser_code");
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProperties.get]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://2bb80b33-b94c-42c5-8b0e-6bd35ff11fc8-internal/securable-module.js -> resource://2bb80b33-b94c-42c5-8b0e-6bd35ff11fc8-lib/app-paths.js :: <TOP_LEVEL> :: line 63"  data: no]
**\* LOG addons.xpi: shutdown

**Comment by keithamus** [comment]
Seems to be an issue with the "resource:app" flag, which I dont think is available any more in XULRunner 6. See: http://mxr.mozilla.org/mozilla2.0/search?string=resource%3Aapp&find=%2F&findi=&filter=%5E%5B%5E%5C0%5D*%24&hitlimit=&tree=mozilla2.0 vs http://mxr.mozilla.org/mozilla-beta/search?string=resource%3Aapp&find=%2F&findi=&filter=%5E%5B%5E%5C0%5D*%24&hitlimit=&tree=mozilla-beta
