### ISSUE TITLE
Canvas element security issues

### ISSUE THREAD

**Issue by dylanpyle** [mozilla/chromeless#142]
As defined in the w3 spec, `<canvas>` elements have some security specs to ensure that websites aren't doing things like inserting local images then reading data out from those.
(see http://www.w3.org/TR/html5/the-canvas-element.html#security-with-canvas-elements for the full deal)

In chromeless, however, this wouldn't be necessary (if a user is trusting the app itself running on their machine, we can assume that they trust this to read local files etc). However, in situations like the one I just encountered, an NS_ERROR_DOM_SECURITY_ERR exception is still raised.
- Create canvas element
- use canvas.drawImage to draw a (user-specified) local image path on the canvas
- call canvas.toDataURL to read the content of the canvas

This shouldn't be an issue, and I'd love to not have this problem, since it severely impacts what's possible with local files.
Apparently there's an 'origin-clean' flag set on the canvas, and forcing this to always be true would solve this problem (again, I just got this info from the w3 spec above)

Thanks all,
Dylan

**Comment by taboca** [comment]
Would this be solved for you if you use the systemPrivileges true preference? There is an example of that in the code.

**Comment by dylanpyle** [comment]
**edit:** So enableSystemPriveleges fixes this perfectly, ignore my confusion. Thanks taboca for the help! Might be prudent to include this in the Chromeless Documentation "startup parameters" section, since there's not too much info about it floating around.

I am running into an issue where once enableSystemPriveleges is enabled, loaders such as HeadJS and loader.js require an absolute path to loaded files, rather than relative. Weird (and I don't know enough to know the reasons behind this), but for now specifying absolute paths isn't a huge deal, just mildly inconvenient.
