### ISSUE TITLE
Support for native OSX Lion Fullscreen functionality

### ISSUE THREAD

**Issue by ygbr** [mozilla/chromeless#144]
Like the latest betas of Chrome, add the support for native OSX Lion Fullscreen functionality to chromeless generated apps would be very nice on applications developed for OSX. Other OS's can fall to regular fullscreen implementation.

**Comment by benfrancis** [comment]
Out of interest, does the current full screen function still work in Lion?

**Comment by richardanaya** [comment]
I have osx lion, the existing full screen works in webian and in the fullscreen api test.
