### ISSUE TITLE
Fetcher is not Working! URL does not exist for any binary dist of xulrunner.

### ISSUE THREAD

**Issue by ygbr** [mozilla/chromeless#145]
The URL for 2.0 xulrunner sdk no longer exists:

<p>The requested URL /pub/mozilla.org/xulrunner/releases/2.0/sdk/xulrunner-2.0.en-US.mac-i386.sdk.tar.bz2 was not found on this server.</p>

<hr>

<address>Apache Server at releases.mozilla.org Port 80</address>

**Comment by dstensnes** [comment]
True that. Contents of http://releases.mozilla.org/pub/mozilla.org/xulrunner/releases/ is:

<pre>
[DIR]   1.9.0.11/       11-Jun-2009 21:36   -
[DIR]   1.9.1.19/       02-May-2011 08:13   -
[DIR]   3.6.21/         31-Aug-2011 06:44   -
[DIR]   6.0/            12-Aug-2011 01:08   -
[DIR]   7.0b2/          26-Aug-2011 10:37   -
[DIR]   7.0b3/          31-Aug-2011 02:40   - 
</pre>

**Comment by keithamus** [comment]
Can also confirm. Tried to change xulrunner to version 6 (in `impl/mozfetcher/_config.py`) but hitting lots of issues trying to get the packaged app running now.
