### ISSUE TITLE
localStorage doesnt work with enableSystemPrivileges

### ISSUE THREAD

**Issue by dylanpyle** [mozilla/chromeless#147]
Exactly as it sounds; setting the `"enableSystemPrivileges": true` flag on an app (including the localStorage example app), breaks localStorage functionality, throwing the following error:

 `info: Uncaught-Exception: 'uncaught exception: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDOMStorageWindow.localStorage]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: chromeless://main/browser_code/main.js :: updateThings :: line 5"  data: no]' in file '' at line 0, col 0 (147)`

**Comment by ddayan** [comment]
I'm experiencing the same issue.
