### ISSUE TITLE
IndexedDB doesn't work

### ISSUE THREAD

**Issue by ddayan** [mozilla/chromeless#149]
info: Uncaught-Exception: 'uncaught exception: [Exception... "The operation failed for reasons unrelated to the database itself and not covered by any other error code."  code: "1" nsresult: "0x80660001 (NS_ERROR_DOM_INDEXEDDB_UNKNOWN_ERR)"  location: "chromeless://main/browser_code/script.js Line: 5"]' in file '' at line 0, col 0 (147)

Code:
var indexedDB = window.indexedDB || window.webkitIndexedDB || window.mozIndexedDB;
[Break On This Error] var request = IndexedDB.open("faves"); 

IndexedDB doesn't work locally on firefox, from my understanding it's because of file:// permissions. Is there anything I need to do to make IndexedDB work on chromeless?

**Comment by invoice2go** [comment]
any update on this yet?? very important issue for us in regards to using chromeless...

**Comment by benfrancis** [comment]
There's some discussion about this in this bug filed against Mozilla core https://bugzilla.mozilla.org/show_bug.cgi?id=643318

The problem is that any page served from file:// would be access the data saved by any other page served from file:// so there needs to be some mechanism to deal with this.

**Comment by invoice2go** [comment]
Thanks for the link ... very helpful. I guess it will take some time to
resolve though.

On Thu, Dec 22, 2011 at 11:24 PM, Ben Francis <
reply@reply.github.com
