### ISSUE TITLE
LSOpenURLsWithRole failed on first run

### ISSUE THREAD

**Issue by toonhello** [mozilla/chromeless#154]
I'm trying to run the ./chromless for the first time in mac osx 10.7.1
After a correct download and extraction of xulrunner, it failed ith the following error:

extracting xulrunner-6.0.2.en-US.mac-i386.sdk.tar.bz2
Using Browser HTML at '/Users/myname/Desktop/mozilla-chromeless-5b11a04/examples/first_browser/index.html'
app code path: /Users/myname/Desktop/mozilla-chromeless-5b11a04/examples/first_browser/index.html
And logging to '/tmp/tmpDYtbDt'
Building application in >/Users/myname/Desktop/mozilla-chromeless-5b11a04/build/My First Browser.app< ...
  ... copying in xulrunner binaries
  ... writing Info.plist
  ... placing xulrunner binary
  ... creating resources directory
Building xulrunner app in >/Users/myname/Desktop/mozilla-chromeless-5b11a04/build/My First Browser.app/Contents/Resources< ...
  ... copying application template
  ... creating application.ini
  ... copying in CommonJS packages
  ... copying in browser code (/Users/myname/Desktop/mozilla-chromeless-5b11a04/examples/first_browser)
  ... writing application info file
  ... writing harness options
xul app generated in build/My First Browser.app/Contents/Resources
opening '/Users/myname/Desktop/mozilla-chromeless-5b11a04/build/My First Browser.app'
LSOpenURLsWithRole() failed with error -10810 for the file /Users/myname/Desktop/mozilla-chromeless-5b11a04/build/My First Browser.app.

**Comment by hugoduncan** [comment]
fwiw, I have the same error with conkeror on 10.7.2

**Comment by nicolasH** [comment]
Hi

I see the same issue, both when I create the browser with no option and with the appify option. The system log error is as follow:

Nov 28 15:15:03 Ikki-8 [0x0-0x71071].My First Browser[3076]: Could not find the Mozilla runtime.
Nov 28 15:15:03 Ikki-8 com.apple.launchd.peruser.501[205]([0x0-0x71071].My First Browser[3076]): Exited with exit code: 1

I could run webian shell as dowloaded from its homepage.

**Comment by fendent** [comment]
Look in the file:

```
(...)/build/My First Browser.app/Contents/Resources/application.ini
```

You should see:

```
[Gecko]
MinVersion=x.x.x
MaxVersion=x.x.x
```

Now check if the XUL Runner SDK you downloaded is out of those bounds. This is the most common reason why you'd get that error.

**Comment by nicolasH** [comment]
[Gecko]
MinVersion=6.0.2
MaxVersion=6.0.2

The xulrunner sdk version is the one Chromeless gets from mozilla's server: 
xulrunner-6.0.2.en-US.mac-i386.sdk.tar.bz2

My machine is a Core 2 Duo:
the result of `arch` is i386

If I use the Contents/MacOS/xulrunner binary from webian shell (from http://webian.org/shell/download/) in My First Browser it works.

If I just use either of these two commands:

```
chromeless appify
chromeless 
```

it does not work, I still have the error above.
