### ISSUE TITLE
ui/session sample error

### ISSUE THREAD

**Issue by HashNuke** [mozilla/chromeless#16]
./run ui/session/index.html

When the 'go' button is clicked on a popup with the following javascript error is shown:
"TypeError: document.getElementById("content").addTab is not a function"

Environment details:
Mozilla XULRunner 1.9.2.12 - 20101027183423
Ubuntu 10.10
If my browser version matters, Firefox 3.6.12

**Comment by taboca** [comment]
Could you test the new browser-session/index.html example instead?

**Comment by taboca** [comment]
This sample needs to be rewriten as now we deprecated the use of the XBL-based tabbrowser implementation.

**Comment by lloyd** [comment]
issue seems obsolete, this sample no longer exists and tests/session demonstrates storing to session storage.
