### ISSUE TITLE
hAS cHROMELESS BEEN tOTALLY aBANDONED??????

### ISSUE THREAD

**Issue by itsN1X** [mozilla/chromeless#172]

**Comment by taboca** [comment]
You can try to use Electron, or, if you want a Mozilla option, Positron.

**Comment by itsN1X** [comment]
Thanks @taboca , i'm already into exploring electron these days..

**Comment by itsN1X** [comment]
It's 2018 and we're still being dominated by Two engines. $wasm.rescue $
