### ISSUE TITLE
NSPlugin Viewer Warning

### ISSUE THREAD

**Issue by HashNuke** [mozilla/chromeless#18]
To reproduce:

./run ui/session/index.html

Enter techcrunch.com or mashable.com in the address bar and the following error appears in the console.

**\* NSPlugin Viewer  **\* WARNING: unhandled variable 18 (<unknown variable>) in NPN_GetValue()

Environment details:
Mozilla XULRunner 1.9.2.12 - 20101027183423
Ubuntu 10.10
If my browser version matters, Firefox 3.6.12

**Comment by lloyd** [comment]
I wonder if this issue is still relevant on latest?
