### ISSUE TITLE
Inner browsers should not access top level or parent window

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#20]
Right now we are using iframes as the inner-browsers. If the inner content should not access the parent browser. The use case, testcase , that should fail is the framebuster example from Lloyd: 

http://github.com/mozilla/chromeless/commit/b5ae774aa258f0ab2a597ff25595c2e0e9db3048

**Comment by lloyd** [comment]
marcio, do we address this in commit e98696a4a219667460b7e2eaecb7b2f1e654047f ?

**Comment by taboca** [comment]
No, the case we fixed iframe busting was the fork ( just landed it here https://github.com/taboca/chromeless/tree/21f11fd56bea4db87c290eb8ae44a6c16210c4ce ) work I did using XUL-based browser implementation, but using code taken from the using the XBL-based tabbrowser implementation. It also allows history controls ( back, forward, stop, reload ) it also allows the history state recover, for example, when one clicks back, the scrollbar of the prior page is placed properly in the saved state, it also allowed us to test the concept and API definitions for progress listeners, for example to monitor page progress of loading.

**Comment by lloyd** [comment]
marcio, if you're content with fd1db1a95310133486e398aad3e7376ae9383883,  we can close this issue

**Comment by lloyd** [comment]
closing this issue.  If we make a change which breaks our anti-framebusting stuff, or we find a page which can _still_ bust, then we should open a new issue.
