### ISSUE TITLE
API - require("canvas-proxy") 

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#22]
HTML developer needs API to take snapshot of page thumbnails. We have this in place but we need a review to be able to control various parameters, such as width, height, aspect ratio, and scale.

**Comment by lloyd** [comment]
can we think of a better name for this api?  how about "thumbnailer" or something that indicates it's about getting images of running web content...

**Comment by lloyd** [comment]
is this a duplicate of #7 ?
