### ISSUE TITLE
API - require("history")

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#24]
API so HTML browser developer can traverse a browser's history.

**Comment by paulrouget** [comment]
Right now, changes in the history has to be tracked by hand.
Would easier to be able to do iframe.history.back(); or

var gHistory = require("history");
var h = gHistory.track(iframe);
h.back();

**Comment by lloyd** [comment]
+1

**Comment by taboca** [comment]
+1 ( hehe I am the bug reporters, so make that 2 please ) and also got motivated to add here due to a thread from the Webian -> Shell project, from Chromeless contributor Ben Francis. He wants to trackdown history. 

I am moving to 0.4 just to poke Lloyd = driver's team.
