### ISSUE TITLE
Way to bypass XULRunner fetch install mode

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#30]
In some systems we may have an existing XULRunner runtime. If a XULRunner runtime is provided, or a bypass option is used as a parameter, our ./chromeless test script should simply use the existing runtime. 

This case is also supported by the idea that if a local repository / fetch fails, existing XULRunner frameworks, or Firefox, could be used instead. A problem I had is: 

```
Fetching xulrunner, 371 bytes from ftp.mozilla.org
| 0%                                                               100% |
|***********************************************************************| 
Traceback (most recent call last):
 File "./chromeless", line 72, in <module>
   f.run()
 File "/Users/marciogalli/Desktop/chromeless/mozilla/repository/chromeless- nov16/chromeless/impl/mozfetcher/_fetcher.py", line 142, in run
   self._fetch(descriptor)
 File "/Users/marciogalli/Desktop/chromeless/mozilla/repository/chromeless-nov16/chromeless/impl/mozfetcher/_fetcher.py", line 111, in _fetch
   raise RuntimeError("download failure!  md5 mismatch!")
RuntimeError: download failure!  md5 mismatch!
```

But I do have 3 XULRunners installed.

**Comment by lloyd** [comment]
371 bytes?  that's not right.  is this problem reproducible?

**Comment by taboca** [comment]
http://ftp.mozilla.org/pub/mozilla.org/xulrunner/nightly/latest-trunk/xulrunner-2.0b7pre.en-US.mac-i386.sdk.tar.bz2 is not available. 

Maybe using a permalink URL like the actual build date instead the latest directory, but anyways this bug was not about that and about giving an option to pick a XULRunner. BTW I am totally fine this option to be: hack the chromeless.file so then in that case, I have no strong opinion if we mark this bug invalid, just wanted to present my use case.

**Comment by lloyd** [comment]
oh.  We should fix the issue this bug isn't about tho! :)

In terms of the issue this bug _is_ about, I'm fine with including instructions for how to point to a different XULRunner, but would prefer to only support one version of xulrunner at a time (and even hack the application.ini to clearly indicate the versions that we "officially support" and have been tested).  Otherwise I fear this will cost us too much in terms of testing and support.

**Comment by lloyd** [comment]
I guess I'm going to close this issue down.  I'm still very much interested in locking ourselves to a specific version of xulrunner.  I'm going to gently dig my heels in...  

We do however have explicit support for outputting a xulrunner app, and I think we should keep that up.  So a developer could export a xulrunner app, then modify version numbers and run it under a different version with a big YMMV caveat?
