### ISSUE TITLE
Preferences in ./template/defaults directory is not installed in installable XULRunner ZIP 

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#32]
We have a ./template/default directory with a preferences JavaScript file in it. This is currently being ignored by the cfx/build system. If you check in ./impl/cuddlefish/runner.py: 

```
class XulrunnerAppProfile(mozrunner.Profile):
    preferences = {'browser.dom.window.dump.enabled': True,
                   'javascript.options.strict': True}
```

The above are the only preferences installed. I think the best here is simply to use the preferences.js file in the ./template/defaults/preferences/prefs.js

**Comment by taboca** [comment]
This is a place to do that : https://github.com/taboca/chromeless/commit/2e0e97cdcd558299952bcb82e8aaa208eb50d783#diff-2

**Comment by lloyd** [comment]
addressed in appify branch, we simply copy over the template from impl/appifier/resources/template/...

so closing issue.

We might want to provide some clean way for the developer to adjust these preferences, for now they'd have to manually hack em.  seems like something we can just wait until someone asks for tho, lots of other juicy issues out there.

**Comment by taboca** [comment]
But then the developer 3rd-party, would have to modify the template? The template itself would become the place for a developer to hack in? Or we move some prefs.js from the ./examples/myapp/ in the template generation time?
