### ISSUE TITLE
Need a way to stop loading content in an iframe

### ISSUE THREAD

**Issue by lloyd** [mozilla/chromeless#34]
This could be accomplished in the vein of the iframe as browser approach:

```
require("iframe-controls").stop(Node);
```

or we could inject functions accessible to browser code on the iframe

```
document.getElementId('myContentIFrame').stop();
```

The latter might be slightly more difficult.  Thoughts on API?

**Comment by taboca** [comment]
SHA: 3f6e45de7a42d62a3e99c8c93d69b34fcccac00e

**Comment by lloyd** [comment]
sure we might want to refine the api, but the feature seems to work in first_browser. closing.
