### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by lloyd** [mozilla/chromeless#42]
there is some support for notifications in both addon-kit and gecko, we should wrap and expose a simple way for apps to throw toast.

**Comment by mikedeboer** [comment]
Titanium 'borrowed' the Fluid.app API for this:
- http://developer.appcelerator.com/apidoc/desktop/latest/Titanium.Notification-module

That API will be compatible across platforms (Growl/ libnotify/ windows custom)

**Comment by mikedeboer** [comment]
The addon-sdk also has a 'notifications' module, but the API doesn't seem to do Growl notifications just yet. It might be a limitation in the xulrunner version we are using(?) If so, than we might consider upgrading to a newer version...

**Comment by mikedeboer** [comment]
I tried upgrading XulRunner to b12pre (by changing the _config.py values in impl/mozfetcher), but after a correct download and extraction, it failed to launch the app with the following error:

```
LSOpenURLsWithRole() failed with error -10810 for the file /Volumes/(...)/chromeless/build/My Chromeless App.app.
```

... So I reverted back to b7pre... :(

**Comment by lloyd** [comment]
I can look at this, yes I can.  maybe tomorrow.  It looks like an issue in appification (maybe sdk layout has changed).

**Comment by lloyd** [comment]
now that we're upgraded to 4.0, desktop notifications should be acheivable with what's already in platform:

https://bugzilla.mozilla.org/show_bug.cgi?id=573588
https://developer.mozilla.org/en/XPCOM_Interface_Reference/nsIDOMDesktopNotification

**Comment by lloyd** [comment]
throwing this in the 0.3 milestone as a stretch goal.
