### ISSUE TITLE
API: Ability to Open Window 

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#43]
HTML/JS developer needs an API that allows a script to open/launch a new window. We may also think and test what is the current behavior when a JavaScript attempts to launch a window, if it works or not, and how another script ( extension perhaps ) would be able to intercept - popup blocking function.

**Comment by CoderPuppy** [comment]
Working on it but the DOMContentLoaded isn't working the event target isn't right

**Comment by taboca** [comment]
Note from community -- elected this Window subject to this 0.3 milestone. 

http://groups.google.com/group/mozilla-labs/browse_thread/thread/90359653908f54fc

**Comment by taboca** [comment]
First note here is that window.openDialog ( http://mxr.mozilla.org/mozilla-central/source/dom/interfaces/base/nsIDOMJSWindow.idl ) works when high sys privileges are turned on, and fails, with a propoer security exception, when the HTML does not have higher privileges. Notice that while openDialog does that ( works || security ) the window.open does not behave likewise. 

Related interesting documentation: 
https://wiki.mozilla.org/DocShell:Window_targeting

Also tested a XULRunner app that is not related to Chromeless and was able to reproduce the problem, first, then also to fix, following some notes from online posts. It turns out we are not alone here a lot of questions online about this ( dump "0x80004005 (NS_ERROR_FAILURE) [nsIDOMJSWindow.open]" to google and see ). The XULRunner folks recommendation was basically to add something like this to the prefs: 

pref("browser.chromeURL","chrome://myappwindow/content/myappwindow.xul");

And I did, my other XULRunner kiosk app worked fine. But Chromeless continued to fail with: 

[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMJSWindow.open]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"

**Comment by taboca** [comment]
It turns out the static XUL file, that has to be the same as pref("browser.chromeURL","chrome://myappwindow/content/myappwindow.xul"); also requires to be XUL window with a XUL browser element in it. Then it worked.

**Comment by CoderPuppy** [comment]
It didn't work for me, it blocked  the navigation

**Comment by ghost** [comment]
Doesn't work for me, too.
When I click the button to open google (in tests/new_window/index.html) I get:

<pre>
info: navigation blocked for: about:blank
info: navigation blocked for: http://www.google.com/
</pre>

When I click the button to open app code I get:

<pre>
info: navigation blocked for: about:blank
info: navigation blocked for: resource://app/new_window.html
</pre>

Tested on Linux and Windows with the current master branch from github.
git log: commit 4e6c980479b0f91b76830dc7b58ff6ae9a0b3978

Please reopen the issue
