### ISSUE TITLE
API: Running script prior to launching first visible window

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#44]
We currently have a main.js file under packages/chromeless. This is the initial script that is executed. When it runs, it opens a window, then it loads the initial developer's code, the browser path HTML file that is passed as a static argument. 

We may want to revisit this and let, or engage the developer, to launch code before the first visible window is active. One approach is to encourage them to write in the main.js ( or call another script from there ). So then, it would up to a developer to launch their other HTML files. The use case is for applications that may want to launch various windows based on preferences, or some other windowless apps. 

Another approach is to think that a very first HTML is can be a hidden window ( depending on prefs or JSON ). Then it would give the developer a chance to do things before launching additional visible windows.

**Comment by CoderPuppy** [comment]
How would I do this? Maybe like this.

<pre>
if(ai.notRunBrowser) {
      // TODO: Load and run browser_code/main.js
      /* Maybe this
      require("../../browser_code/main").main(options, testCallbacks);
      or this
      require('run').main(options, testCallbacks);
      
      but where would it find run
      */
} else {
    ...
}
</pre>

**Comment by taboca** [comment]
Yes, sort of a possible design, but then leaving main to the app developer as a choice. The design thinking I am inclined: 

Each chromeless app to become a directory like this: 

```
./developer-app/lib/main.js ( main entry point, but a lot simpler than current main.js app ) 
./developer-app/data/* al lthe sorts of data you want, HTML etc
./developer-app/template-override/defaults ( you can place prefs here directly -- no need to go through extra JSON )
./developer-app/template-override/components ( you can move libraries and binaries here )
./developer-app/tests/test-my-app.js
```

**Comment by CoderPuppy** [comment]
Yeah

Looks good.

Would Chromeless find main.js
