### ISSUE TITLE
Support transparent applications

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#5]
## 
## Moving existing bugs in Etherpad to this project here.

The module, chromeless-window, is used from the main.js chromeless app. It is the initial startpoint to the application and loads the main application HTML. We need to simplify that module and allow to launch initial window in transparent mode.

**Comment by lloyd** [comment]
how do you envision things working?  Should the transparency on the body of the HTML entry point be the sold parameter which controls transparency of the specified application window?

**Comment by taboca** [comment]
I think, related to another bug, the initial entry point, main.js, should be more exposed to the developer. They may want to allow first window in transparent, opaque, or to not even launch a window. That is why I think the packages/chromeless-kit should be away from the sub-directory of the packages/chromeless. In other words, chromeless/lib/main.js should become very small and hackable.

**Comment by taboca** [comment]
More food: 

http://groups.google.com/group/mozilla.dev.extensions/browse_thread/thread/fc6a30bc67f1030f#
