### ISSUE TITLE
API - 'process' (was: Need a way to execute files from the filesystem)

### ISSUE THREAD

**Issue by Flyingmana** [mozilla/chromeless#54]
I saw that you can read and write files.
I wish to be able to execute other files to reuse existing applications from within chromeless

**Comment by lloyd** [comment]
I think this is a fine idea.  I wonder if we could get some inspiration from this api from node.js?: 

http://nodejs.org/docs/v0.3.7/api/process.html

I think that the [nsIProcess](https://developer.mozilla.org/en/XPCOM_Interface_Reference/nsIProcess) module has most of the features we'll want in a first pass, ready to script from javascript.

**Comment by lloyd** [comment]
http://mozilla.github.com/chromeless/#module/lib/child_process
