### ISSUE TITLE
Browser API: ability to stop page load

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#56]
This is from the groups thread, from a developer Mr. Ben Francis: 

https://groups.google.com/d/msg/mozilla-labs/2T6stq1IZYA/RFPW3HuVTiQJ

"P.S. Can I have a browser stop button and page title helper functions in Chromeless please?"

**Comment by lloyd** [comment]
this is a duplicate of Issue #34 and Issue #35 !
