### ISSUE TITLE
Full screen broken under Linux

### ISSUE THREAD

**Issue by benfrancis** [mozilla/chromeless#57]
To reproduce:
- Run ./chromeless examples/thumbnails under Linux (tested with Ubuntu 10.04)
- Click full screen button

Expected outcome:
Browser displays full screen

Actual ouctome:
20px grey stripe across top of screen

Works fine  under OS X.

Most likely related to this commit which replaced the misc library which previously handled full screen toggling:
https://github.com/mozilla/chromeless/commit/841f61920b12ca46ec3d24f6914892b8845884ba

**Comment by lloyd** [comment]
hey there!  as you saw, I recently landed several changes, so master is a bit unstable at the moment.  

Working on fixing special iframe dom events, then will jump in and check this out.  fwiw, seems to work find on my arch linux box.

Lots of apis getting moved around, I hope to blog up the major changes today or tomorrow.

**Comment by lloyd** [comment]
port thumbnails example to new APIs.  probably Closed by a7b93a74ede2a05293812a9a4d6ecbbd8e64fbeb (works fine now for me on linux)

**Comment by benfrancis** [comment]
Sorry, but I'm still seeing this problem with the thumbnails and fisheye examples (as well as my own project) under Ubuntu 10.04, I've tested it on two different boxes

![Screenshot of problem](https://lh3.googleusercontent.com/_sK1WXA9nT54/TVUGtqq73PI/AAAAAAAAABQ/w68z7Ct6GAY/s800/chromeless_full_screen_problem.png)

**Comment by lloyd** [comment]
Oh, sorry.  I understand now.  This is a dup of issue #58, that grey stripe is the menubar.  Will add param to hide it in the next few days.

**Comment by benfrancis** [comment]
Aah, that explains why it looks fine on OS X :)
