### ISSUE TITLE
require('simple-storage') fails

### ISSUE THREAD

**Issue by slbug** [mozilla/chromeless#59]
my js:

<pre>
const storage = require('simple-storage');
</pre>

console:

<pre>
info: require of 'simple-storage' failed: TypeError: file.mkpath is not a function

info: Uncaught-Exception: 'TypeError: file.mkpath is not a function' in file 'resource://jid0-ve0baysox4snijgmmjrgl4kfm2w-api-utils-lib/securable-module.js -> resource://jid0-ve0baysox4snijgmmjrgl4kfm2w-addon-kit-lib/simple-storage.js' at line 215, col 0 (22)
</pre>

**Comment by lloyd** [comment]
even though I&#39;m not really happy with the simple-storage API, it&#39;s implemented now.  Repair the module (broken during the fs/path/file breakout), and port documentation so it&#39;s visible.  Closed by 58e14be692da104aacddc7adf6f2b9276bd30cf9.

**Comment by lloyd** [comment]
For reference, API docs now available:  http://mozilla.github.com/chromeless/#module/addon-kit/simple-storage

thanks for the report, slbug!
