### ISSUE TITLE
Does not run on windows

### ISSUE THREAD

**Issue by ghost** [mozilla/chromeless#60]
running chromeless.bat fails, says unsupported operating system. Tested on windows7 x64

**Comment by lloyd** [comment]
I just tested (and fixed) chromeless on windows7 x64.  But I wouldn't have expected the problems on windows to cause your error.  What's the precise error message you saw?  What version of python are you running?

**Comment by ghost** [comment]
python 2.5 it was. looks like switching to python 2.6 solves the issue
