### ISSUE TITLE
API - require('file-picker')

### ISSUE THREAD

**Issue by lloyd** [mozilla/chromeless#66]
We should wrap [nsIFilePicker](https://developer.mozilla.org/en/nsIFilePicker) in a nice abstraction for easy use by application code.

**Comment by lloyd** [comment]
See fc5439a9b468a36f394d69a7ed4eb97e91073312, it's a functional but feature bare first pass which demonstrates how to do the adminstrative stuff.  Get current active app window, instantiate nsIFilePicker, etc.

**Comment by past** [comment]
I implemented mode selection as well, and sent a pull request.

**Comment by lloyd** [comment]
pulled!  the basic feature is now present, closing this bug and we can open new ones as new features are desired in the file-picker
