### ISSUE TITLE
XP - "python: can't open path 'c:\Documents ': [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by majtophat** [mozilla/chromeless#71]
I am getting this error:
python: can't open path 'c:\Documents ': [Errno 2] No such file or directory

I have the chromeless directory synced in "C:\Documents and Settings\myName\chromeless" I think this is just an error with how it is taking the path of the files. It works fine when I move chromeless to the root of my c drive.

**Comment by santiagomartinez** [comment]
Write the path between quotation marks. Like this:
python "C:\Documents and Settings\myName\chromeless"
