### ISSUE TITLE
ensure that flash can be used inside a chromeless app

### ISSUE THREAD

**Issue by lloyd** [mozilla/chromeless#72]
This bug is to track exploration and documentation of what it takes to use flash from a chromeless app.  Will chromeless just detect an installed plugin?  can we make it simple to bundle binary plugins (flash and other npapi goodness) with apps?

**Comment by dunkfordyce** [comment]
symlinking libflashplayer.so into xulrunner plugins seems to get flash running but i get alot of these warnings when running a page with flash in:

(xulrunner-bin:1152): Gdk-WARNING **: XID collision, trouble ahead

**Comment by sbeckeriv** [comment]
youtube.com is working with the thumbnail example on mac osx 10.6.7

**Comment by lloyd** [comment]
good enough for now!  I confirmed both linux and osx.

re "trouble ahead", a google search reveals that this is really not our problem.

**Comment by askmeaks** [comment]
I tried using chromeless (recent pull from git) on a Fedora 64 bit machine. I symlinked libflashplayer.so (adobe flash beta 11-x86_64) into **./build/xulrunner/** and **./build/xulrunner/plugins**. But it didnot work. Flash content is still not displayed.

**Comment by askmeaks** [comment]
Symlinking has not yet worked. I've already tried with both 32 bit and 64 bit libflashplayer.so library files.

**Comment by askmeaks** [comment]
Finally got it working. You have to symlink libflashplayer.so into ~/.mozilla/plugins/
