### ISSUE TITLE
JavaScript window alert function does not work 

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#75]
This is what I see: 

Uncaught-Exception: 'uncaught exception: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIWindowWatcher.openWindow]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: file:///Users/marciogalli/Desktop/chromeless/mozilla/repository/v2/Mar01-Mar16-branches/chromeless/build/xulrunner-sdk/bin/components/nsPrompter.js :: anonymous :: line 379"  data: no]' in file 'resource://app/index.html' at line 6, col 0 (147)

**Comment by davidmurdoch** [comment]
I noticed this too. Though, sometimes it does work. I think there may be some race-condition involved here or you may have to wait till after DOMready or onload to use it.

**Comment by CoderPuppy** [comment]
Its working for me. I updated the window system in [my fork of it](http://github.com/drewyoung1/chromeless/).

**Comment by taboca** [comment]
The alert is back, the openDialog is good, the window.open fails -- see also issue #43

**Comment by lloyd** [comment]
taboca, I didn't understand that last comment?  did some of the changes for issue #43 improve the situation with alerts fired at initial application code load time?
