### ISSUE TITLE
Exposing the XULRunner app template to developers 

### ISSUE THREAD

**Issue by taboca** [mozilla/chromeless#76]
The case: 

A developer wants to insert a few libraries in the components directory. An example: rainbow API is currently available as multiple binaries, one per each OS, Mac, Linux, and Windows. If a developer places the Mozilla Rainbow libraries in the components directory of a XULRunner-compatible app, then the XPCOM component is exposed, thus it allows the creation of video (OGG) record function into the app. 

Current status: 

A python module, ./impl/appify, looks under a certain sub-directory, the xulrunner.template, and copies it to a directory that becomes the developer's final app. And if a developer wants to create an application that has specific library, she/he needs to copy the file to ./impl/appify/resources/xulrunner.template/components. However, this design is not good because it would require a developer to always move files to and from this directory depending on the app. 

Initial reasoning for proposal:

Developer should be able to pass a template folder, like Jetpack accepts, or perhaps, if we detect certain directory, under the developer's root directory, then we simply do more template magic to place the files in the right output directory.

**Comment by lloyd** [comment]
hmmm, I'll think about this.  At a high level, the value of chromeless is to establish a clear line between mozilla specific code, and standard javascript.

As we expose more of the mozilla platform directly, I become unclear as to the real value of chromeless.  

Perhaps we'd want to build extensions like rainbow into the platform, but I'm not convinced that we should take steps to make chromeless support this level of customization -- at some point the consumer can just fork.

**Comment by taboca** [comment]
I understand that point of view too -- it's a conflict for me. I understand the strategy of basic = default = easy to run = most of cases, maybe a bit of documentation is good to solve the other cases. I just wanted to file this as I see the first case came up, that is why I pointed rainbow support.
