### ISSUE TITLE
Fullscreen does not hide taskbar

### ISSUE THREAD

**Issue by nyroDev** [mozilla/chromeless#80]
When switching to fullscreen mode using this code:
    const fullscreen = require("fullscreen");
    fullscreen.toggle(window);

The window taskbar is not hidden.

I tested on Windows XP, Vista and 7.

Is there any workaround to do that or is it a chromeless bug?

**Comment by lloyd** [comment]
Maybe the recent upgrade to xul 2.0 fixes this, because I just tried on my win7 vm and the task bar hides properly.  Can you retest in your environment with latest to confirm?

**Comment by nyroDev** [comment]
yes, this bug is now fixed! (tested on XP, Vista and 7)
The only thing is when you want to switch in fullscreen automatically at the begginign of your JS code, you have to put the code
  fullscreen.toggle(window);

in a setTimeout.

**Comment by lloyd** [comment]
rad!  I'll update the documentation of toggle to reflect this, and will close the issue!  Thanks for retesting so promptly!

**Comment by lloyd** [comment]
http://mozilla.github.com/chromeless/#module/chromeless-kit/fullscreen

**Comment by nyroDev** [comment]
Perfect, thanks!

**Comment by taboca** [comment]
Cross-ref : https://github.com/mozilla/chromeless/issues/70
