### ISSUE TITLE
drastically simplify packages/

### ISSUE THREAD

**Issue by lloyd** [mozilla/chromeless#82]
packages/ should be renamed to "modules" and all built in modules should be put there.  The hier under this should be lib/ and test/

Underneath lib/ modules can be grouped with a directory hierarchy as required.  

The existing structure is overdesigned for our needs in chromeless, and that deep structure combined with the presence of tons of modules that don't work and aren't meaningful make the project hard to approach and contribute to.

</ definitive tone>

**Comment by lloyd** [comment]
I've thought about it, and have a proposed approach.  Here's what I'm thinking, in the form of an excerpt of an email I just wrote:

---

As you may have seen, we have problems related to code organization in chromeless right now, and the next thing on my list is to embark on a mission to solve them.  I guess it's somewhat analogous to you guys, but we have a very clear distinction in chromeless that seems to override everything else in terms of priority.  That's what will calls "High-Level"/"Low Level": what libraries are meant to be used by chromeless "application code".  Experimental vs. Supported is a close second, and third is the "by application area" (a useful way to structure documentation, and the tagging approach seems like a really good start).

Based on my own view of priorities, I was going to embark on a restructuring of chromeless libraries today, and here's my rough approach (FWIW, YMMV, etc):

New directory structure:
- `lib/*.js` -- supported, "high-level" modules, interesting to "application code".
- `lib/internal/*.js` -- "low-level" modules interesting to module authors.  in fact               maybe it's a hard error for application code to include these guys, and              they don't show up (in the most prominent view, at least) of the docs.
- `lib/experimental/*.js` -- experimental "high-level" modules.  These are interesting              to application code, but it must include them using the "experimental"               prefix.  Idea here is that application authors are forced to realize what              APIs are not stable, so its really expectation setting.

To complement that structure I planned to improve/rework/<fix what we broke> the packaging system so that application authors can include their own modules/ directories, along with samples and docs.

**Comment by taboca** [comment]
Not a change for the developer right? I am fine. It does not change the structure of the target app too, which is good. I don't have strong opinion on packages => modules. For me packages = apps anyway -- tht is sort of a line I am driving for now on I feel. I want chromeless to be an application that accepts sub-scripts.

**Comment by lloyd** [comment]
Cool.  

Yeah I'm going for zero change for the developer for the first pass.

Part of this restructuring kills all of the complex notion of "packages", so a couple things that I want to fix along the way:
- issue #64, give the developer a way to augment include paths ("module_paths" in appinfo.json?)
- issue #31, first pass: indicating to the documentation system internally (for use by module authors) vs. public (for use by application code)

Once I get that stuff done, I'll merge to trunk!

lloyd
