### ISSUE TITLE
write short tutorial of first application and using require()

### ISSUE THREAD

**Issue by lloyd** [mozilla/chromeless#89]
currently placeholder links exist in the docs.  These two bits of documentation should be written as they can be pretty general and won't change too much (despite the fact that we expect APIs will flip and flop a bunch), and they're _really_ high value for a newcomer to the project.

**Comment by kyleconroy** [comment]
In the mean time, could some place holder content be put into the documentation? I thought that my browser was broken and I couldn't see those two sections.
