### ISSUE TITLE
Can't get textures working with WebGL (NS_ERROR_FAILURE at nsIDOMWebGLRenderingContext.texImage2D)

### ISSUE THREAD

**Issue by coreh** [mozilla/chromeless#90]
Hey there, first I would like to congratulate you guys on the incredible progress being made with this project. I've been dreaming with something like this for some time.

Here's an issue I'm having: When I try to run my WebGL game with chromeless, I get the following error (printed on the terminal):

```
info: Uncaught-Exception: 'uncaught exception: [Exception... "Failure arg 5 [nsIDOMWebGLRenderingContext.texImage2D]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://app/js/ResourceManager.js :: <TOP_LEVEL> :: line 28"  data: no]' in file '' at line 0, col 0 (147)
```

Here's the affected piece of code (`js/ResourceManager.js`):

```
[...]
var image = document.createElement("img");
image.onload = function() {
    var texture = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, texture);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, image);  // LINE 28 ***
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER,  gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER,  gl.LINEAR);
    gl.generateMipmap(gl.TEXTURE_2D);
    [...]
};
image.src = path;
[...]
```

I have highlighted the line where the exception was thrown. I suspect this might be some issue with the same origin policy, (and the `resource://` scheme) but I might be wrong. The bundled WebGL demo seems to be unafected by this, since it uses a `data:` URI.

Thanks in advance.

_Edit:_ Forgot to mention: I'm running Mac OS X 10.6.6. The source of my game is available here, if needed for testing: https://github.com/Coreh/WebSonic

**Comment by taboca** [comment]
Hey Coreh - looks interesting your project. I want to follow up with your stuff here but I get the following error: 

With Firrfox 4 and also Chromeless 0.2 

info: Uncaught-Exception: 'uncaught exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMHTMLCanvasElement.getContext]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://app/js/GraphicsEngine.js :: <TOP_LEVEL> :: line 12"  data: no]' in file '' at line 0, col 0 (147)

**Comment by coreh** [comment]
Hey taboca, thanks! :-)

Hmmm. I've seen this happen before on a "clean" Windows install, without third party video drivers (from the manufacter) present. Perhaps the same can happen if you're on linux without proprietary drivers.

The offending line seems to be:

```
if (gl = canvas.getContext("experimental-webgl", glParams)) {
```

So yeah, I think it means it couldn't initialize WebGL. Can you run normally other WebGL content on Firefox, or the WebGL demo that comes bundled with Chromeless?

**Comment by taboca** [comment]
Yes,  you are right. I did not have the GL stuff our tests system, and indeed is it not available. Also Aurora shows it is not available when using WebGL demos at http://www.chromeexperiments.com/detail/clouds/?f=webgl

**Comment by taboca** [comment]
Hi Coreh, 

Okay I looked WebGL problems thread online and looks like we have to use force WebGL, which you can tests if you edit your local : 

```
./impl/appifier/resources/xulrunner.template/defaults/preferences/prefs.js
```

Add the 

```
pref("webgl.force-enabled",true); 
```

And let me know. I was able to get the local webgl demo to work but not yours entirely. Now I see the texture problem but at least the WebGL context exists now.

**Comment by coreh** [comment]
Hey taboca, I'm still getting the same error at the same line, even after adding the pref you mentioned and "rebuilding" the App with the `./chromeless` command.

I've tested the game in Aurora 2011-04-29, and it works just fine there.

By the way, I managed to get the game running in chromeless by _loading it from a remote origin inside an iframe_:

```
<!DOCTYPE html>
<iframe src="http://coreh.github.com/WebSonic">
```

I'm really thinking this is a same-origin thing, and that it has to do with the `resource:` URI used in chromeless.

**Comment by taboca** [comment]
ok. With the pref I mentioned the Chromeless webgl demo is working for me. I still was not able to get your web version to work in Aurora.

**Comment by taboca** [comment]
The demo crashed Firefox 4 but I see no report being generated. Weird. And with Chrome it works the timer counter you have but I see nothing. All black in the screen, even after 1 minute counting.

**Comment by coreh** [comment]
That's really strange. I think this really shows how WebGL compability still needs to improve everywhere. Did the engine display anything on the screen in Chrome, at least? Any error messages?

**Comment by kevinxbrown** [comment]
I get the same error in FF5, when I do this: 
                var m = document.createElement('ImageTexture');
                m.setAttribute("url", image);
                a.appendChild(m);
HOWEVER - it works fine when I use an image 128x128px square (71dpi), but not when I use one which is 115px square (96dpi)... still investigating

**Comment by taboca** [comment]
Yes, good point. The build in example in WebGL I did is even square. I forgot about that.  Using this texturization solution with WebGL depends on square images. I also wonder if we could find an efficient way to bind a image from the HTML to the WebGL context, something faster, maybe like mozElement.

**Comment by kevinxbrown** [comment]
After a bit of experimenting, square images of 128px seem to work... less does not (I tried 115 and 100 and 130) none worked - only the 128px!

They are all loading fine according to firebug, just not appearing on my cube (except the 128px).

This behaviour is the same in Google chrome. I'm using v1.2.0 of x3dom.

**Comment by kevinxbrown** [comment]
I have a 115 x 115 image I need to use.

This _definitely_ isn't the right fix, but I have found 128 in the x3dom, and changed it to 115 (in most places), and commented out  the "if (tex._vf.scale) { " line in x3dom.js.... this works for me now with 115x115 images (all I need). However I look forward to replacing my hacked x3dom with an official version at some point!

**Comment by taboca** [comment]
16x16? 32x32? 64, 128, 256, 512? etc?

**Comment by kevinxbrown** [comment]
So, I've also tried the (128x128) image on a local server - works fine, but tried it on a server with a different domain name, and it again doesn't work. I guess x-domain getting in the way somewhere

**Comment by kevinxbrown** [comment]
@taboca - tried 32x32, and 512x512 - working well :-)

**Comment by kevinxbrown** [comment]
Now got the pictures working x-domain using a local proxy, but not ideal to have to do this of course. So in summary I think 2 fixes are needed: 
1. scaling to any size (not just powers-of-2)
2. somehow loading of the image from the browser rather than javascript, so the x-domain issue is avoided.

**Comment by taboca** [comment]
and may I add a general interesting thing, 3. which is to have a way that is more optimal solution to add videos and images as textures of 3D. We need to maintain these 3 items and bring up this as bugs or to a discussion with mozilla platform engineers. This is outside Chromeless and yet Chromeless wants to consume.

**Comment by taboca** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=662570
