### ISSUE TITLE
"The document contains no data" alert upon opening any URL

### ISSUE THREAD

**Issue by nikolaplejic** [mozilla/chromeless#91]
Ubuntu 10.04 64bit, Python 2.6.5

Running `./chromeless` opens up the `examples/first_browser/index.html` browser, but when I enter any URL in the textbox and click "go", an alert pops up saying "The document contains no data".

The same thing happens when:
- running the `examples/fisheyetabs/index.html` browser, entering a URL and clicking "go";
- running the `examples/webgl/index.html` browser (right away on window load).

Here's the console output I got when running the `first_browser` example: http://pastie.org/1849912.

I'm not sure if this is related or helpful, but I noticed this problem as well:
- running the `examples/ui/index.html` example opens the browser, but clicking on the buttons does nothing (the debugger says, i.e.: `info: Uncaught-Exception: 'uncaught exception: Error: Module "ui/tray" not found' in file '' at line 0, col 0 (147)`).

The same thing happens regardless of the version used (0.2, 0.1, or the latest revision from the master branch). I tried poking around the code a bit, but couldn't pinpoint the issue. 

If I can provide any additional information, please let me know.

Thanks.

**Comment by davidmurdoch** [comment]
I got this once yesterday with latest branch but couldn't reproduce again. Could you try again on your machine with latest?

**Comment by nikolaplejic** [comment]
I just did a pull of the master branch and ran chromeless -- unfortunately, the problem is still there. Here's the console output I got this time: http://pastie.org/2044223 (it seems to be no different than the one in my original post).

If I can do anything else to help identify the problem, please let me know.

**Comment by davidmurdoch** [comment]
what URLs are you testing?

**Comment by nikolaplejic** [comment]
Here are a few I tried right now: 
- any local path (file:///...) loads fine;
- http://localhost/ -- loads fine;
- http://127.0.0.1/ -- returns "The document contains no data";
- http://google.com, http://facebook.com, http://yahoo.com, http://[ip-address-here] -- these all return "The document contains no data" alert;
- http://foo.lh/ (any Apache VirtualHost on my machine, defined in /etc/hosts) returns "The document contains no data".

All of them work fine in all other browsers on my machine.

**Comment by davidmurdoch** [comment]
I'm wondering if this has anything to do with IPv6.

**Comment by davidmurdoch** [comment]
Did some more digging on this....

If you add the following line to your appified application's defaults/preferences/pref.js the alert will go away:

```
pref("browser.xul.error_pages.enabled", true);
```

and an error page will be displayed instead.

Lloyd, is there a way to set preferences in the browser code?

**Comment by davidmurdoch** [comment]
This seems to be affect only linux systems.

Another odd thing...facebook's favicon will not load even if accessed via &lt;img src=... />
