### ISSUE TITLE
Uncaught-Exception: 'ReferenceError: require is not defined

### ISSUE THREAD

**Issue by sbeckeriv** [mozilla/chromeless#96]
I am working off an old copy of the thumbnail example. I moved most of the javascript to shot.js. I recently re-merged my fork and everything seem to have gone bad.  full code https://github.com/sbeckeriv/chromeless  becker branch Thanks! 

info: debugger enabled
info: Uncaught-Exception: 'require is not defined' in file 'chromeless://main/browser_code/index.html' at line 154, col 0 (1)

info: Uncaught-Exception: 'ReferenceError: require is not defined' in file 'chromeless://main/browser_code/index.html' at line 154, col 0 (1)

info: Uncaught-Exception: 'WebSocket is not defined' in file 'chromeless://main/browser_code/websocket.js' at line 2, col 0 (1)

 

<html>
  <head>
    
    <title>Rocky</title>

```
<!-- we can use basic flexbox layout! -->
<style type="text/css" media="screen">

  body {
    background-color: #999;
    padding: 0;
    margin: 0;
  }

  #browserHeader {
    width: 100%;
    text-align: center;
  }

  #browserHeader form { 
  } 
  #awesomeBox {
    font-size: 120%;
    margin-right: 20px;
    width:240px;
  }

  .security_secure { 
    -moz-transition-property: background-color;
    -moz-transition-duration: 1s;
    -moz-transition-delay: 0s;
    background-color:lightblue;
  }  
  .security_insecure { 
    -moz-transition-property: background-color;
    -moz-transition-duration: 1s;
    -moz-transition-delay: 0s;
    background-color:yellow;
  }  
  .security_broken { 
    -moz-transition-property: background-color;
    -moz-transition-duration: 1s;
    -moz-transition-delay: 0s;
    background-color:red;
  }  

  #browserContentArea {
    -moz-box-flex: 1;
    -webkit-box-flex: 1;
    box-flex: 1;
    display: -moz-box;
    display: -webkit-box;
    display: box;
    border: 1px solid green;
    margin-top:0;
  }


  #outer {
    margin: 0;
    width: 100%;
    height: 100%;
    display: -moz-box;
    display: -webkit-box;
    display: box;
    -moz-box-orient: vertical;
    -webkit-box-orient: vertical;
    box-orient: vertical;
  }

  .browser { 
    border: 1px solid blue;
    box-flex: 1;
    -moz-box-flex: 1;
    -webkit-box-flex: 1;
    width: 100%;
    height: 100%;
  } 

  .browser_selected { 
    display:block;
  } 

  .browser_hidden { 
    display:none;
  } 

  #thumbsNavigator { 
    height:32px;
    background-color:red;
    overflow:hidden;
  } 

  .thumb_img { 
    -moz-transition-property: width,height;
    -moz-transition-duration: .5s;
    -moz-transition-delay: .5s;
    width:32px;
    height:32px;
    opacity:.6;
    margin-left:5px;;
    overflow:hidden;
  } 

  .thumb_img:hover { 
  -moz-transition-property: width,height;
  -moz-transition-duration: .5s;
  -moz-transition-delay: 0s;
  height:220px;
  width:240px;
  } 

  .thumb_selected { 
  -moz-transition-property: opacity;
  -moz-transition-duration: .5s;
  opacity:1;
  -moz-transition-delay: 0s;
  width:240px;
  height:40px;
  } 
</style>
```

  </head>
  <body>
    <div id="outer">
      <div id="thumbsNavigator">
      </div>
      <div id="browserHeader">
        <form>
          <input id="awesomeBox"  type="text" value="http://www.google.com" />
          <input type="submit" id="buttonGo"  value="go"></input>
          <button id="buttonNew" >New</button>
          <button id="buttonPersist" >All</button>
          <button id="buttonFull" >Full</button>
        </form>
      </div>
      <div id="browserContentArea">
         
      </div>
    </div>
  </body>
  
  <script type="text/javascript" src="jquery-min.js"></script>

  <script type="text/javascript">
const {Cc,Ci,Cu} = require("chrome");
const fullscreen  = require("fullscreen");
const url         = require("url");
var camera = require("canvas-proxy");

  </script>
    <script type="text/javascript" src="websocket.js"></script>
  <script type="text/javascript" src="shot.js"></script>
</html>

**Comment by taboca** [comment]
Are you using the enableSystemPrivileges true in appinfo.js?

**Comment by sbeckeriv** [comment]
Yes I am.  I was under the impression this was the only way to access the iframe data?

**Comment by taboca** [comment]
Okay, so can you test your dev app ( older thumb exmaple ) with the master recent commit? It turns out that, due to  XULRunner 2 changes, our sys priv support was broken in 0.2 milestone. I checked in e033c400c253af3ce2bb26c98e1a2fe6e651fa5a please let me know

**Comment by sbeckeriv** [comment]
Looks like this has fixed my issue. thank you!
